name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: Build and deploy to dev
    runs-on: ubuntu-latest

    steps:
      - name: Build and run tests
        run: |
          echo "Building and running tests..."
      - name: Deploy to dev
        run: |
          echo "Deploying to dev..."
