name: Deploy release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        environment: [Acceptance, Production]
    uses: ./deploy.yaml
    with:
      environment: ${{ matrix.environment }}
