name: Deploy to Test
on:
  workflow_run:
    workflows: [CI]
    types: [completed]

run-name: ${{ github.event.workflow_run.head_commit.message }}
jobs:
  deploy-test:
    name: Deploy
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: Test
      ref: ${{ github.ref }}
      run-job: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets: inherit
