name: Deploy release

on:
  push:
    branches:
      - main

jobs:
  deploy-acc:
    name: Deploy to Acc
    environment: acceptance
    uses: ./.github/workflows/deploy.yaml

  deploy-prd:
    name: Deploy to Prd
    environment: production
    uses: ./.github/workflows/deploy.yaml
