name: Deploy release

on:
  push:
    branches:
      - main

jobs:
  deploy-acc:
    name: Deploy
    permissions:
      contents: write
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: Acceptance

  deploy-acc:
    name: Deploy
    permissions:
      contents: write
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: Production
