name: Deploy release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        environment: [Acceptance, Production]
    permissions:
      contents: write
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ matrix.environment }}
