name: Release

on:
  push:
    tags:
      - v*

jobs:
  deploy-acc:
    name: Deploy
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment: Acceptance
    secrets: inherit

  deploy-prd:
    name: Deploy
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment: Production
    secrets: inherit
