name: "一 deploy"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: true
        type: string
      run-job:
        type: boolean

env:
  EXAMPLE_VARIABLE: ${{ vars.EXAMPLE_VARIABLE }}
  ENVIRONMENT: ${{ vars.ENVIRONMENT_STAGE }}
  SECRET_VARIABLE: ${{ secrets.SECRET_VARIABLE }}

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    if: ${{ inputs.run-job }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-tags: true
      - name: Print environment specific variable
        run: |
          echo "EXAMPLE_VARIABLE: $EXAMPLE_VARIABLE. SECRET: $SECRET_VARIABLE"
      # Workflow permissions need to be set to 'Read and write' to be able to push
      - name: Deploy frontend 🚀
        run: |
          git checkout -B $SECRET_VARIABLE
          git push origin $SECRET_VARIABLE --force
